exclude:
  - README.md
  - /*.pdn
  - /*.xcf
  - /Thumbs.db

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

comments: true
hidecollaboratorinfo: false

vk-support: false
fb-support: false
tweeter-dupport: false
