exclude:
  - README.md
  - /*.pdn
  - /*.xcf
  - /Thumbs.db

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

permalink: '/posts/:year/:month/:day/:title.html'
paginate: 5
paginate_path: "/?page=:num"
url: 'hideons.github.io/jm-organization.github.io'
