exclude:
  - README.md
  - /*.pdn
  - /*.xcf
  - /Thumbs.db
  
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  
paginate: 5
paginate_path: "/?page=:num"
url: 'hideons.github.io/jm-organization.github.io'
