- main-title: "JM Organization"
  main-url: "https://jm-organization.github.io/"

exclude:
  - README.md
  - /*.pdn
  - /*.xcf
  - /Thumbs.db

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

comments: true
hidecollaboratorinfo: false

vk-support: true
