jmorg:
  title: "JM Organization"
  url: "https://jm-organization.github.io/"

  - home:
    title: "Главная"
    url: "https://jm-organization.github.io/"

  - about:
    title: "О нас"
    url: "https://jm-organization.github.io/"
    - contacts:
      title: "Контакты"
      url: "https://jm-organization.github.io/"

  - portfolio:
    title: "Портфолио"
    url: "https://jm-organization.github.io/"