main-title: "JM Organization"
main-url: "https://jm-organization.github.io/"

- title: "Главная"
  url: "https://jm-organization.github.io/"

- title: "О нас"
  url: "https://jm-organization.github.io/"

- title: "Контакты"
  url: "https://jm-organization.github.io/"

- title: "Портфолио"
  url: "https://jm-organization.github.io/"