#---------------------
#  Шаблон
#---------------------
#- service:
#  id:
#  fixed:
#  fixed-state:
#  price:
#  info:
#----------------------

currency: "&#8372;"
curr-title: "Гривен"

services:
  # +
  - service: "Сайты под ключ"
    id: "sites-in-key"
    fixed: true
    fixed-state: active
    price: от 2499
    info: Информация

  # -
  - service: "Разработка дизайна для сайта"
    id: "site-design"
    fixed: true
    fixed-state:
    price: от 1900
    info: Информация

  # -
  - service: "Оптимизация"
    id: "optimization"
    fixed: false
    fixed-state:
    price: от 1000
    info: Информация

  # -
  - service: "Проектирование Баз данных"
    id: "base-date-create"
    fixed: true
    fixed-state:
    price: 1399
    info: Информация

  # -
  - service: "Разработка плагинов под различные CMS"
    id: "develop-plugins-for-cms"
    fixed: false
    fixed-state:
    price: от 1000
    info: Информация

  # +
  - service: "Техническая поддержка"
    id: "tech-support"
    fixed: true
    fixed-state:
    price: от 50
    info: Информация

  # +
  - service: "Техническая поддержка серверов Minecraft"
    id: "minecraft-servers-support"
    fixed: true
    fixed-state:
    price: 1000
    info: Информация
